/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SpsAbi } from "./SpsAbi";
export * as factories from "./factories";
export { SpsAbi__factory } from "./factories/SpsAbi__factory";
