import { Result } from '@steem-monsters/lib-monad';
import {
    OperationData,
    PromiseManager,
    AdminMembership,
    AdminAction,
    Action,
    EventLog,
    Trx,
    ActionFactory,
    ActionRouter,
    Compute,
    route,
    addRoutesForClass,
} from '@steem-monsters/splinterlands-validator';
import { create_promise, create_promise_legacy } from '../schema';
import { MakeActionFactory } from '../utils';
import { TransitionManager } from '../../features/transition';
import { inject, injectable } from 'tsyringe';

/**
 * Legacy admin-only create_promise action.
 * Used before the delegation_offer_block transition.
 * Requires a promise ID to be provided.
 */
export class LegacyCreatePromiseAction extends AdminAction<typeof create_promise_legacy.actionSchema> {
    constructor(op: OperationData, data: unknown, index: number, private readonly promiseManager: PromiseManager, adminMembership: AdminMembership) {
        super(adminMembership, create_promise_legacy, op, data, index);
    }

    override async validate(trx?: Trx | undefined): Promise<boolean> {
        if (!(await super.validate(trx))) {
            return false;
        }

        const validateResult = await this.promiseManager.validateCreatePromise(
            {
                type: this.params.type,
                id: this.params.id,
                controllers: this.params.controllers,
                params: this.params.params,
                fulfill_timeout_seconds: this.params.fulfill_timeout_seconds,
            },
            this,
            trx,
        );

        if (Result.isErr(validateResult)) {
            throw validateResult.error;
        }

        return true;
    }

    async process(trx?: Trx): Promise<EventLog[]> {
        return this.promiseManager.createPromise(
            {
                type: this.params.type,
                id: this.params.id,
                controllers: this.params.controllers,
                params: this.params.params,
                fulfill_timeout_seconds: this.params.fulfill_timeout_seconds,
            },
            this,
            trx,
        );
    }
}

/**
 * New create_promise action (non-admin).
 * Used after the delegation_offer_block transition.
 * Allows null promise ID (auto-generated by PromiseManager).
 * Non-admins can create promises for certain types (e.g., delegation_offer).
 */
export class CreatePromiseAction extends Action<typeof create_promise.actionSchema> {
    constructor(op: OperationData, data: unknown, index: number, private readonly promiseManager: PromiseManager) {
        super(create_promise, op, data, index);
    }

    override async validate(trx?: Trx | undefined): Promise<boolean> {
        const validateResult = await this.promiseManager.validateCreatePromise(
            {
                type: this.params.type,
                id: this.params.id ?? null,
                controllers: this.params.controllers,
                params: this.params.params,
                fulfill_timeout_seconds: this.params.fulfill_timeout_seconds,
            },
            this,
            trx,
        );

        if (Result.isErr(validateResult)) {
            throw validateResult.error;
        }

        return true;
    }

    async process(trx?: Trx): Promise<EventLog[]> {
        return this.promiseManager.createPromise(
            {
                type: this.params.type,
                id: this.params.id ?? null,
                controllers: this.params.controllers,
                params: this.params.params,
                fulfill_timeout_seconds: this.params.fulfill_timeout_seconds,
            },
            this,
            trx,
        );
    }
}

const LegacyBuilder = MakeActionFactory(LegacyCreatePromiseAction, PromiseManager, AdminMembership);
const NewBuilder = MakeActionFactory(CreatePromiseAction, PromiseManager);

@injectable()
export class Router extends ActionRouter<LegacyCreatePromiseAction | CreatePromiseAction> {
    private static _transitionBlock = Number.MAX_SAFE_INTEGER;

    static transitionBlock(_c: Compute) {
        return Router._transitionBlock;
    }

    @route(create_promise_legacy.action_name, { to_block: Router.transitionBlock })
    readonly legacyBuilder: ActionFactory<LegacyCreatePromiseAction>;

    @route(create_promise.action_name, { from_block: Router.transitionBlock })
    readonly newBuilder: ActionFactory<CreatePromiseAction>;

    constructor(
        @inject(LegacyBuilder) legacyBuilder: ActionFactory<LegacyCreatePromiseAction>,
        @inject(NewBuilder) newBuilder: ActionFactory<CreatePromiseAction>,
        @inject(TransitionManager) transitionManager: TransitionManager,
    ) {
        super();
        Router._transitionBlock = transitionManager.transitionPoints.delegation_offer_block;
        this.legacyBuilder = legacyBuilder;
        this.newBuilder = newBuilder;
        addRoutesForClass(Router, this);
    }
}
