-- 61083045

-- SELECT MAX(block_num) FROM transactions

DELETE FROM config WHERE group_name NOT IN ('$root', 'sps');
DELETE FROM config WHERE group_name = '$root' AND name NOT IN ('admin_accounts', 'proxy_accounts');

DELETE FROM balances WHERE token NOT IN ('SPS', 'SPSP');
DELETE FROM balances WHERE balance = 0;

DROP SCHEMA IF EXISTS datadog CASCADE;
DROP SCHEMA IF EXISTS archive CASCADE;
DROP SCHEMA IF EXISTS website CASCADE;
DROP SCHEMA IF EXISTS reporting CASCADE;

ALTER TABLE transactions DROP COLUMN IF EXISTS steem_price;
ALTER TABLE transactions DROP COLUMN IF EXISTS sbd_price;

DROP TABLE IF EXISTS account_create CASCADE;
DROP TABLE IF EXISTS airdrops CASCADE;
DROP TABLE IF EXISTS battle_cards CASCADE;
DROP TABLE IF EXISTS battle_queue CASCADE;
DROP TABLE IF EXISTS battles CASCADE;
DROP TABLE IF EXISTS bcx CASCADE;
DROP TABLE IF EXISTS brawl_cycles CASCADE;
DROP TABLE IF EXISTS brawl_guild_records CASCADE;
DROP TABLE IF EXISTS card_details CASCADE;
DROP TABLE IF EXISTS card_transfer_history CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS chat CASCADE;
DROP TABLE IF EXISTS coin_payments_tx CASCADE;
DROP TABLE IF EXISTS combined_cards CASCADE;
DROP TABLE IF EXISTS dec_swaps CASCADE;
DROP TABLE IF EXISTS emails CASCADE;
DROP TABLE IF EXISTS event_log CASCADE;
DROP TABLE IF EXISTS event_logs CASCADE;
DROP TABLE IF EXISTS gifts CASCADE;
DROP TABLE IF EXISTS guild_announcements CASCADE;
DROP TABLE IF EXISTS guild_contributions CASCADE;
DROP TABLE IF EXISTS guild_members CASCADE;
DROP TABLE IF EXISTS guild_tournament_frays CASCADE;
DROP TABLE IF EXISTS guilds CASCADE;
DROP TABLE IF EXISTS ip_data CASCADE;
DROP TABLE IF EXISTS item_details CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS market_cards CASCADE;
DROP TABLE IF EXISTS market_cards_completed CASCADE;
DROP TABLE IF EXISTS market_items CASCADE;
DROP TABLE IF EXISTS market_items_completed CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS packs CASCADE;
DROP TABLE IF EXISTS payment_addresses CASCADE;
DROP TABLE IF EXISTS paypal_tx CASCADE;
DROP TABLE IF EXISTS player_items CASCADE;
DROP TABLE IF EXISTS player_skins CASCADE;
DROP TABLE IF EXISTS player_wallets CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS promo_codes CASCADE;
DROP TABLE IF EXISTS purchases CASCADE;
DROP TABLE IF EXISTS quest_rewards CASCADE;
DROP TABLE IF EXISTS quests CASCADE;
DROP TABLE IF EXISTS rental_history CASCADE;
DROP TABLE IF EXISTS rshares_by_block CASCADE;
DROP TABLE IF EXISTS saved_teams CASCADE;
DROP TABLE IF EXISTS season_players CASCADE;
DROP TABLE IF EXISTS season_rewards CASCADE;
DROP TABLE IF EXISTS seasons CASCADE;
DROP TABLE IF EXISTS shop_purchases CASCADE;
DROP TABLE IF EXISTS skins CASCADE;
DROP TABLE IF EXISTS steem_engine_transactions CASCADE;
DROP TABLE IF EXISTS stripe_charges CASCADE;
DROP TABLE IF EXISTS tournament_battles CASCADE;
DROP TABLE IF EXISTS tournament_matchups CASCADE;
DROP TABLE IF EXISTS tournament_players CASCADE;
DROP TABLE IF EXISTS tournament_rounds CASCADE;
DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS transaction_cards CASCADE;
DROP TABLE IF EXISTS transactions_recent CASCADE;
DROP TABLE IF EXISTS tron_transactions CASCADE;
DROP TABLE IF EXISTS battle_queue_hold CASCADE;
DROP TABLE IF EXISTS battle_queue_old CASCADE;
DROP TABLE IF EXISTS battles_master CASCADE;
DROP TABLE IF EXISTS transaction_block_dates CASCADE;

DROP FUNCTION IF EXISTS awsdms_intercept_ddl CASCADE;
DROP TABLE IF EXISTS awsdms_ddl_audit CASCADE;

DROP VIEW IF EXISTS credits_market_purchases;
DROP VIEW IF EXISTS mystery_potions;