##
## Original code from https://github.com/dbsystel/postgresql-partman-container
## Licensed under the Apache License, Version 2.0
##
## Modified by the SPS DAO 2025
##

ARG POSTGRESQL_VERSION="17"

FROM postgres:$POSTGRESQL_VERSION-alpine AS builder
ARG PARTMAN_VERSION="v5.2.4"
ARG PARTMAN_CHECKSUM="8328a00ce1a55a5c9173d4adbf251e784fed62413fb76bba89dd893749a720a5ecb25ee668eb0b826b8e1f2b89d9dd7da219fd797bfd9ab1a43d05f5b3ac494f"
USER root

RUN apk add --no-cache wget gcc make musl-dev postgresql-dev $DOCKER_PG_LLVM_DEPS

RUN wget "https://github.com/pgpartman/pg_partman/archive/refs/tags/${PARTMAN_VERSION}.tar.gz" \
    && echo "${PARTMAN_CHECKSUM}  ${PARTMAN_VERSION}.tar.gz" | sha512sum -c \
    && tar zxf ${PARTMAN_VERSION}.tar.gz && cd pg_partman-${PARTMAN_VERSION#v}\
    && make \
    && make install

FROM postgres:$POSTGRESQL_VERSION-alpine

COPY --from=builder /usr/local/share/postgresql/extension/pg_partman* /usr/local/share/postgresql/extension/
COPY --from=builder /usr/local/lib/postgresql/pg_partman_bgw.so /usr/local/lib/postgresql/
COPY --from=builder pg_partman-*/bin/common/* /usr/local/bin/

COPY ./setup-preload.sh /docker-entrypoint-initdb.d/

USER postgres
