---
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
      packages: read
    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
          registry-url: 'https://npm.pkg.github.com'

      # Set timestamps to last git modification date
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
      - name: Overwrite validator/structure.sql if needed
        working-directory: scripts
        run: ./ci-lazy-regenerate-structure.sh
      - run: npm ci --silent
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run lint validator-lib
      - run: npm run lint sps-validator
      - run: npm run lint lib-monad
      - run: npm run build --if-present validator-lib
      - run: npm run build --if-present sps-validator
      - run: npm run build --if-present lib-monad
      - run: npm run test validator-lib
      - run: npm run test sps-validator
      - run: npm run test lib-monad
