name: Pages

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install and Build
              env:
                  PUBLIC_URL: https://steem-monsters.github.io/splinterlands-validator
                  REACT_APP_BASEPATH: splinterlands-validator
              run: |
                  npm ci
                  npx nx openapi sps-validator-ui
                  npx nx build sps-validator-ui --configuration=production
                  cp dist/apps/sps-validator-ui/index.html dist/apps/sps-validator-ui/404.html

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.3.0
              with:
                  branch: gh-pages
                  folder: dist/apps/sps-validator-ui
