name: Pages

on:
    push:
        branches:
            - master

jobs:
    build:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install and Build
              run: |
                  npm ci
                  npx nx build sps-validator-ui --configuration=production
                  cp dist/apps/sps-validator-ui/index.html dist/apps/sps-validator-ui/404.html
              env:
                  BASE_HREF: /SPS-Validator/
                  VALIDATOR_PREFIX: sl-qavsm_
                  VALIDATOR_API_URL: https://splinterlands-validator.validator.qa.splinterlands.com

            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
              with:
                  path: dist/apps/sps-validator-ui/

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
